### PR TITLE
Add custom fetch option

### PR DESCRIPTION
**Pull request by hd-o**
## Changes

Add `fetch` property to `ClientOptions` for custom implementations

Relates: drwpow/openapi-typescript#1125 drwpow/openapi-fetch#41 drwpow/openapi-typescript#1126

## Checklist

- [x] Tests updated
- [x] README updated

### CODE REVIEW

**Comment by hd-o** [comment]
@drwpow May I add a [github workflow][workflow] to run tests and lint on open PRs?

[workflow]: https://docs.github.com/en/actions/using-workflows/about-workflows

**Comment by drwpow** [comment]
> @drwpow May I add a [github workflow](https://docs.github.com/en/actions/using-workflows/about-workflows) to run tests and lint on open PRs?

? there are GitHub workflows already set up. what are you suggesting?

**Comment by hd-o** [comment]
@drwpow Sorry, I overlooked because of a [type error][error] in the editor but not in the PR checks. All good

[error]: https://github.com/drwpow/openapi-fetch/pull/51/commits/58270bbbf2ccede92b455c16f2c9a376bc0f81a7

**Review by drwpow — APPROVED** [review]

**Comment by drwpow** [comment]
Thank you! Great feature, and great tests.

**Pull request merged**
